# Generated by Django 4.2.8 on 2023-12-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_footer', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': ('Setup',),
                'verbose_name_plural': 'Setups',
            },
        ),
    ]
